apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgres://flaskuser:flaskpassword@postgres-service:5432/flaskdb"
